package io.github.myceliumlang.arguments

import io.github.myceliumlang.Minecraftable

enum class Gamerule(private val mcName: String, public val type: Class<*>) : Minecraftable {
    AnnounceAdvancements("announceAdvancements", Boolean::class.java),
    BlockExplosionDropDecay("blockExplosionDropDecay", Boolean::class.java),
    CommandBlocksEnabled("commandBlocksEnabled", Boolean::class.java),
    CommandBlockOutput("commandBlockOutput", Boolean::class.java),
    CommandModificationBlockLimit("commandModificationBlockLimit", Int::class.java),
    DisableElytraMovementCheck("disableElytraMovementCheck", Boolean::class.java),
    DisableRaids("disableRaids", Boolean::class.java),
    DoDaylightCycle("doDaylightCycle", Boolean::class.java),
    DoEntityDrops("doEntityDrops", Boolean::class.java),
    DoFireTick("doFireTick", Boolean::class.java),
    DoInsomnia("doInsomnia", Boolean::class.java),
    DoImmediateRespawn("doImmediateRespawn", Boolean::class.java),
    DoLimitedCrafting("doLimitedCrafting", Boolean::class.java),
    DoMobLoot("doMobLoot", Boolean::class.java),
    DoMobSpawning("doMobSpawning", Boolean::class.java),
    DoPatrolSpawning("doPatrolSpawning", Boolean::class.java),
    DoTileDrops("doTileDrops", Boolean::class.java),
    DoTraderSpawning("doTraderSpawning", Boolean::class.java),
    DoVinesSpread("doVinesSpread", Boolean::class.java),
    DoWeatherCycle("doWeatherCycle", Boolean::class.java),
    DoWardenSpawning("doWardenSpawning", Boolean::class.java),
    DrowningDamage("drowningDamage", Boolean::class.java),
    EnderPearlsVanishOnDeath("enderPearlsVanishOnDeath", Boolean::class.java),
    FallDamage("fallDamage", Boolean::class.java),
    FireDamage("fireDamage", Boolean::class.java),
    ForgiveDeadPlayers("forgiveDeadPlayers", Boolean::class.java),
    FreezeDamage("freezeDamage", Boolean::class.java),
    GlobalSoundEvents("globalSoundEvents", Boolean::class.java),
    FunctionCommandLimit("functionCommandLimit", Int::class.java),
    KeepInventory("keepInventory", Boolean::class.java),
    LavaSourceConversion("lavaSourceConversion", Boolean::class.java),
    LogAdminCommands("logAdminCommands", Boolean::class.java),
    MaxCommandChainLength("maxCommandChainLength", Int::class.java),
    MaxCommandForkCount("maxCommandForkCount", Int::class.java),
    MaxEntityCramming("maxEntityCramming", Int::class.java),
    MobExplosionDropDecay("mobExplosionDropDecay", Boolean::class.java),
    MobGriefing("mobGriefing", Boolean::class.java),
    NaturalRegeneration("naturalRegeneration", Boolean::class.java),
    PlayerNetherPortalCreativeDelay("playerNetherPortalCreativeDelay", Int::class.java),
    PlayersSleepingPercentage("playersSleepingPercentage", Int::class.java),
    ProjectilesCanBreakBlocks("projectilesCanBreakBlocks", Boolean::class.java),
    PVP("pvp", Boolean::class.java),
    RandomTickSpeed("randomTickSpeed", Int::class.java),
    RecipesUnlock("recipesUnlock", Boolean::class.java),
    ReducedDebugInfo("reducedDebugInfo", Boolean::class.java),
    RespawnBlocksExplode("respawnBlocksExplode", Boolean::class.java),
    SendCommandFeedback("sendCommandFeedback", Boolean::class.java),
    ShowBorderEffect("showBorderEffect", Boolean::class.java),
    ShowCoordinates("showCoordinates", Boolean::class.java),
    ShowDaysPlayed("showDaysPlayed", Boolean::class.java),
    ShowDeathMessages("showDeathMessages", Boolean::class.java),
    ShowRecipeMessages("showRecipeMessages", Boolean::class.java),
    ShowTags("showTags", Boolean::class.java),
    ShowAccumulationHeight("showAccumulationHeight", Int::class.java),
    SpawnChunkRadius("spawnChunkRadius", Int::class.java),
    SpawnRadius("spawnRadius", Int::class.java),
    SpectatorsGenerateChunks("spectatorsGenerateChunks", Boolean::class.java),
    TNTExplodes("tntExplodes", Boolean::class.java),
    TNTExplosionDropDecay("tntExplosionDropDecay", Boolean::class.java),
    UniversalAnger("universalAnger", Boolean::class.java),
    WaterSourceConversion("waterSourceConversion", Boolean::class.java);

    override fun toMinecraft(): String {
        return mcName
    }
}